/// Generated by AssetsRefGenerator on 2020/04/29
class Res {
  static const String city_background = "images/city_background.jpg";
  static const String homebar = "images/homebar.png";
  static const String location_background = "images/location_background.jpg";
}
